Parse the expiration time as an INT
toptal/haste-server pull request #392
Opened 2021-10-03 21:02 UTC by linus-jansson

Using  .ENV files with haste-server causes the expiration time to be seen as a String. This results in the `expireJS` being enormously large and causes a "value is out of range for type integer" error, in probably most databases  (*postgres* in my case).

https://github.com/toptal/haste-server/blob/5d2965ffc5d9b309ef6d4be9e8c2288c83d72c73/lib/document_stores/postgres.js#L27

2021-11-22 14:43 UTC, deniskaber requested changes
Hello @linus-jansson! Thanks for contributing.
Could you please add radix for `parseInt` so it works as expected for every case.

2021-11-22 14:43 UTC, deniskaber commented on lib/document_stores/postgres.js
> +  this.expireJS = parseInt(options.expire);
```suggestion
  this.expireJS = parseInt(options.expire, 10);
```

2021-11-24 09:40 UTC, linus-jansson commented on lib/document_stores/postgres.js
> +  this.expireJS = parseInt(options.expire);
You are definitely right with adding a radix, didn't think that was a thing so thank you for pointing that out!

2022-01-12 14:33 UTC, konstrybakov approved these changes

2022-02-14 18:23 UTC, filipechagas commented
Hello @linus-jansson 
Thank you once more for contributing!

I'm about to merge your PR but I wanted to ask you one last thing: Can you be so kind to check if after the changes applied by https://github.com/toptal/haste-server/pull/366/files this is still necessary?

2022-02-14 19:48 UTC, merged