Allow permalinking to lines
toptal/haste-server pull request #43
Opened 2013-04-11 22:41 UTC by ammaraskar

Allows you to click on lines and grab a hash based permalink to it in your url bar, much like in github.
### Demonstration: http://paste.md-5.net/pomiqeyeye.cs#L17

There is one hack in here I'm not real proud of: https://github.com/seejohnrun/haste-server/pull/43/files#L3R21 but I can't really figure out a nice way to work around that properly. Basically when you change the hash, it calls the pop event because the history changes. Feel free to offer any better solutions to the problem if you have any.

2018-08-05 05:51 UTC, gt-c commented
Can I expect this to come soon?

2018-08-06 15:31 UTC, seejohnrun commented
@gt-c Just given the age of the PR we'll need some cleanup here / shouldn't be too hard to get it up to date but it'll be a bit before I have time personally

2018-08-12 22:31 UTC, gt-c commented
ok :D thanks!

2022-02-14 18:36 UTC, filipechagas requested changes
Hi @ammaraskar 
Thank  you for contributing!

Can you please verify @seejohnrun comments and also one of my own?
Also, please update the branch with latest `master` changes.

2022-02-14 18:36 UTC, filipechagas commented on static/solarized_dark.css
> +}
Can you please fix EOL?

2022-03-31 02:04 UTC, closed without merging